/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UniformesRouteImport } from './routes/uniformes'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RhRouteImport } from './routes/rh'
import { Route as RematriculaAcompanhamentoRouteImport } from './routes/rematricula-acompanhamento'
import { Route as RematriculaRouteImport } from './routes/rematricula'
import { Route as PortalCantinaRouteImport } from './routes/portal-cantina'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatriculasRouteImport } from './routes/matriculas'
import { Route as MatriculaRouteImport } from './routes/matricula'
import { Route as InadimplenciaRouteImport } from './routes/inadimplencia'
import { Route as FundosRouteImport } from './routes/fundos'
import { Route as FluxoFuturoRouteImport } from './routes/fluxo-futuro'
import { Route as ExtratoBancarioRouteImport } from './routes/extrato-bancario'
import { Route as EstoqueMaterialRouteImport } from './routes/estoque-material'
import { Route as EsportesRouteImport } from './routes/esportes'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as ColoniaRouteImport } from './routes/colonia'
import { Route as CobrancaAutomaticaRouteImport } from './routes/cobranca-automatica'
import { Route as CobrancaRouteImport } from './routes/cobranca'
import { Route as CartaoCreditoRouteImport } from './routes/cartao-credito'
import { Route as CantinaRouteImport } from './routes/cantina'
import { Route as AtendimentoIaRouteImport } from './routes/atendimento-ia'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdmissoesRouteImport } from './routes/admissoes'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UniformesRoute = UniformesRouteImport.update({
  id: '/uniformes',
  path: '/uniformes',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const RematriculaAcompanhamentoRoute =
  RematriculaAcompanhamentoRouteImport.update({
    id: '/rematricula-acompanhamento',
    path: '/rematricula-acompanhamento',
    getParentRoute: () => rootRouteImport,
  } as any)
const RematriculaRoute = RematriculaRouteImport.update({
  id: '/rematricula',
  path: '/rematricula',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCantinaRoute = PortalCantinaRouteImport.update({
  id: '/portal-cantina',
  path: '/portal-cantina',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculasRoute = MatriculasRouteImport.update({
  id: '/matriculas',
  path: '/matriculas',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaRoute = MatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const InadimplenciaRoute = InadimplenciaRouteImport.update({
  id: '/inadimplencia',
  path: '/inadimplencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FundosRoute = FundosRouteImport.update({
  id: '/fundos',
  path: '/fundos',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoFuturoRoute = FluxoFuturoRouteImport.update({
  id: '/fluxo-futuro',
  path: '/fluxo-futuro',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoBancarioRoute = ExtratoBancarioRouteImport.update({
  id: '/extrato-bancario',
  path: '/extrato-bancario',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueMaterialRoute = EstoqueMaterialRouteImport.update({
  id: '/estoque-material',
  path: '/estoque-material',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportesRoute = EsportesRouteImport.update({
  id: '/esportes',
  path: '/esportes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ColoniaRoute = ColoniaRouteImport.update({
  id: '/colonia',
  path: '/colonia',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaAutomaticaRoute = CobrancaAutomaticaRouteImport.update({
  id: '/cobranca-automatica',
  path: '/cobranca-automatica',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaRoute = CobrancaRouteImport.update({
  id: '/cobranca',
  path: '/cobranca',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoCreditoRoute = CartaoCreditoRouteImport.update({
  id: '/cartao-credito',
  path: '/cartao-credito',
  getParentRoute: () => rootRouteImport,
} as any)
const CantinaRoute = CantinaRouteImport.update({
  id: '/cantina',
  path: '/cantina',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoIaRoute = AtendimentoIaRouteImport.update({
  id: '/atendimento-ia',
  path: '/atendimento-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissoesRoute = AdmissoesRouteImport.update({
  id: '/admissoes',
  path: '/admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/agenda': typeof AgendaRoute
  '/atendimento': typeof AtendimentoRoute
  '/atendimento-ia': typeof AtendimentoIaRoute
  '/cantina': typeof CantinaRoute
  '/cartao-credito': typeof CartaoCreditoRoute
  '/cobranca': typeof CobrancaRoute
  '/cobranca-automatica': typeof CobrancaAutomaticaRoute
  '/colonia': typeof ColoniaRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diario': typeof DiarioRoute
  '/documentos': typeof DocumentosRoute
  '/esportes': typeof EsportesRoute
  '/estoque-material': typeof EstoqueMaterialRoute
  '/extrato-bancario': typeof ExtratoBancarioRoute
  '/fluxo-futuro': typeof FluxoFuturoRoute
  '/fundos': typeof FundosRoute
  '/inadimplencia': typeof InadimplenciaRoute
  '/matricula': typeof MatriculaRoute
  '/matriculas': typeof MatriculasRoute
  '/onboarding': typeof OnboardingRoute
  '/portal-cantina': typeof PortalCantinaRoute
  '/rematricula': typeof RematriculaRoute
  '/rematricula-acompanhamento': typeof RematriculaAcompanhamentoRoute
  '/rh': typeof RhRoute
  '/tasks': typeof TasksRoute
  '/uniformes': typeof UniformesRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/agenda': typeof AgendaRoute
  '/atendimento': typeof AtendimentoRoute
  '/atendimento-ia': typeof AtendimentoIaRoute
  '/cantina': typeof CantinaRoute
  '/cartao-credito': typeof CartaoCreditoRoute
  '/cobranca': typeof CobrancaRoute
  '/cobranca-automatica': typeof CobrancaAutomaticaRoute
  '/colonia': typeof ColoniaRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diario': typeof DiarioRoute
  '/documentos': typeof DocumentosRoute
  '/esportes': typeof EsportesRoute
  '/estoque-material': typeof EstoqueMaterialRoute
  '/extrato-bancario': typeof ExtratoBancarioRoute
  '/fluxo-futuro': typeof FluxoFuturoRoute
  '/fundos': typeof FundosRoute
  '/inadimplencia': typeof InadimplenciaRoute
  '/matricula': typeof MatriculaRoute
  '/matriculas': typeof MatriculasRoute
  '/onboarding': typeof OnboardingRoute
  '/portal-cantina': typeof PortalCantinaRoute
  '/rematricula': typeof RematriculaRoute
  '/rematricula-acompanhamento': typeof RematriculaAcompanhamentoRoute
  '/rh': typeof RhRoute
  '/tasks': typeof TasksRoute
  '/uniformes': typeof UniformesRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/agenda': typeof AgendaRoute
  '/atendimento': typeof AtendimentoRoute
  '/atendimento-ia': typeof AtendimentoIaRoute
  '/cantina': typeof CantinaRoute
  '/cartao-credito': typeof CartaoCreditoRoute
  '/cobranca': typeof CobrancaRoute
  '/cobranca-automatica': typeof CobrancaAutomaticaRoute
  '/colonia': typeof ColoniaRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diario': typeof DiarioRoute
  '/documentos': typeof DocumentosRoute
  '/esportes': typeof EsportesRoute
  '/estoque-material': typeof EstoqueMaterialRoute
  '/extrato-bancario': typeof ExtratoBancarioRoute
  '/fluxo-futuro': typeof FluxoFuturoRoute
  '/fundos': typeof FundosRoute
  '/inadimplencia': typeof InadimplenciaRoute
  '/matricula': typeof MatriculaRoute
  '/matriculas': typeof MatriculasRoute
  '/onboarding': typeof OnboardingRoute
  '/portal-cantina': typeof PortalCantinaRoute
  '/rematricula': typeof RematriculaRoute
  '/rematricula-acompanhamento': typeof RematriculaAcompanhamentoRoute
  '/rh': typeof RhRoute
  '/tasks': typeof TasksRoute
  '/uniformes': typeof UniformesRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissoes'
    | '/agenda'
    | '/atendimento'
    | '/atendimento-ia'
    | '/cantina'
    | '/cartao-credito'
    | '/cobranca'
    | '/cobranca-automatica'
    | '/colonia'
    | '/conciliacao'
    | '/configuracoes'
    | '/diario'
    | '/documentos'
    | '/esportes'
    | '/estoque-material'
    | '/extrato-bancario'
    | '/fluxo-futuro'
    | '/fundos'
    | '/inadimplencia'
    | '/matricula'
    | '/matriculas'
    | '/onboarding'
    | '/portal-cantina'
    | '/rematricula'
    | '/rematricula-acompanhamento'
    | '/rh'
    | '/tasks'
    | '/uniformes'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissoes'
    | '/agenda'
    | '/atendimento'
    | '/atendimento-ia'
    | '/cantina'
    | '/cartao-credito'
    | '/cobranca'
    | '/cobranca-automatica'
    | '/colonia'
    | '/conciliacao'
    | '/configuracoes'
    | '/diario'
    | '/documentos'
    | '/esportes'
    | '/estoque-material'
    | '/extrato-bancario'
    | '/fluxo-futuro'
    | '/fundos'
    | '/inadimplencia'
    | '/matricula'
    | '/matriculas'
    | '/onboarding'
    | '/portal-cantina'
    | '/rematricula'
    | '/rematricula-acompanhamento'
    | '/rh'
    | '/tasks'
    | '/uniformes'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/admissoes'
    | '/agenda'
    | '/atendimento'
    | '/atendimento-ia'
    | '/cantina'
    | '/cartao-credito'
    | '/cobranca'
    | '/cobranca-automatica'
    | '/colonia'
    | '/conciliacao'
    | '/configuracoes'
    | '/diario'
    | '/documentos'
    | '/esportes'
    | '/estoque-material'
    | '/extrato-bancario'
    | '/fluxo-futuro'
    | '/fundos'
    | '/inadimplencia'
    | '/matricula'
    | '/matriculas'
    | '/onboarding'
    | '/portal-cantina'
    | '/rematricula'
    | '/rematricula-acompanhamento'
    | '/rh'
    | '/tasks'
    | '/uniformes'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissoesRoute: typeof AdmissoesRoute
  AgendaRoute: typeof AgendaRoute
  AtendimentoRoute: typeof AtendimentoRoute
  AtendimentoIaRoute: typeof AtendimentoIaRoute
  CantinaRoute: typeof CantinaRoute
  CartaoCreditoRoute: typeof CartaoCreditoRoute
  CobrancaRoute: typeof CobrancaRoute
  CobrancaAutomaticaRoute: typeof CobrancaAutomaticaRoute
  ColoniaRoute: typeof ColoniaRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DiarioRoute: typeof DiarioRoute
  DocumentosRoute: typeof DocumentosRoute
  EsportesRoute: typeof EsportesRoute
  EstoqueMaterialRoute: typeof EstoqueMaterialRoute
  ExtratoBancarioRoute: typeof ExtratoBancarioRoute
  FluxoFuturoRoute: typeof FluxoFuturoRoute
  FundosRoute: typeof FundosRoute
  InadimplenciaRoute: typeof InadimplenciaRoute
  MatriculaRoute: typeof MatriculaRoute
  MatriculasRoute: typeof MatriculasRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalCantinaRoute: typeof PortalCantinaRoute
  RematriculaRoute: typeof RematriculaRoute
  RematriculaAcompanhamentoRoute: typeof RematriculaAcompanhamentoRoute
  RhRoute: typeof RhRoute
  TasksRoute: typeof TasksRoute
  UniformesRoute: typeof UniformesRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uniformes': {
      id: '/uniformes'
      path: '/uniformes'
      fullPath: '/uniformes'
      preLoaderRoute: typeof UniformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rematricula-acompanhamento': {
      id: '/rematricula-acompanhamento'
      path: '/rematricula-acompanhamento'
      fullPath: '/rematricula-acompanhamento'
      preLoaderRoute: typeof RematriculaAcompanhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rematricula': {
      id: '/rematricula'
      path: '/rematricula'
      fullPath: '/rematricula'
      preLoaderRoute: typeof RematriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-cantina': {
      id: '/portal-cantina'
      path: '/portal-cantina'
      fullPath: '/portal-cantina'
      preLoaderRoute: typeof PortalCantinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriculas': {
      id: '/matriculas'
      path: '/matriculas'
      fullPath: '/matriculas'
      preLoaderRoute: typeof MatriculasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula': {
      id: '/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof MatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inadimplencia': {
      id: '/inadimplencia'
      path: '/inadimplencia'
      fullPath: '/inadimplencia'
      preLoaderRoute: typeof InadimplenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundos': {
      id: '/fundos'
      path: '/fundos'
      fullPath: '/fundos'
      preLoaderRoute: typeof FundosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-futuro': {
      id: '/fluxo-futuro'
      path: '/fluxo-futuro'
      fullPath: '/fluxo-futuro'
      preLoaderRoute: typeof FluxoFuturoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato-bancario': {
      id: '/extrato-bancario'
      path: '/extrato-bancario'
      fullPath: '/extrato-bancario'
      preLoaderRoute: typeof ExtratoBancarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-material': {
      id: '/estoque-material'
      path: '/estoque-material'
      fullPath: '/estoque-material'
      preLoaderRoute: typeof EstoqueMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esportes': {
      id: '/esportes'
      path: '/esportes'
      fullPath: '/esportes'
      preLoaderRoute: typeof EsportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colonia': {
      id: '/colonia'
      path: '/colonia'
      fullPath: '/colonia'
      preLoaderRoute: typeof ColoniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca-automatica': {
      id: '/cobranca-automatica'
      path: '/cobranca-automatica'
      fullPath: '/cobranca-automatica'
      preLoaderRoute: typeof CobrancaAutomaticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca': {
      id: '/cobranca'
      path: '/cobranca'
      fullPath: '/cobranca'
      preLoaderRoute: typeof CobrancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao-credito': {
      id: '/cartao-credito'
      path: '/cartao-credito'
      fullPath: '/cartao-credito'
      preLoaderRoute: typeof CartaoCreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cantina': {
      id: '/cantina'
      path: '/cantina'
      fullPath: '/cantina'
      preLoaderRoute: typeof CantinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento-ia': {
      id: '/atendimento-ia'
      path: '/atendimento-ia'
      fullPath: '/atendimento-ia'
      preLoaderRoute: typeof AtendimentoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissoes': {
      id: '/admissoes'
      path: '/admissoes'
      fullPath: '/admissoes'
      preLoaderRoute: typeof AdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissoesRoute: AdmissoesRoute,
  AgendaRoute: AgendaRoute,
  AtendimentoRoute: AtendimentoRoute,
  AtendimentoIaRoute: AtendimentoIaRoute,
  CantinaRoute: CantinaRoute,
  CartaoCreditoRoute: CartaoCreditoRoute,
  CobrancaRoute: CobrancaRoute,
  CobrancaAutomaticaRoute: CobrancaAutomaticaRoute,
  ColoniaRoute: ColoniaRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DiarioRoute: DiarioRoute,
  DocumentosRoute: DocumentosRoute,
  EsportesRoute: EsportesRoute,
  EstoqueMaterialRoute: EstoqueMaterialRoute,
  ExtratoBancarioRoute: ExtratoBancarioRoute,
  FluxoFuturoRoute: FluxoFuturoRoute,
  FundosRoute: FundosRoute,
  InadimplenciaRoute: InadimplenciaRoute,
  MatriculaRoute: MatriculaRoute,
  MatriculasRoute: MatriculasRoute,
  OnboardingRoute: OnboardingRoute,
  PortalCantinaRoute: PortalCantinaRoute,
  RematriculaRoute: RematriculaRoute,
  RematriculaAcompanhamentoRoute: RematriculaAcompanhamentoRoute,
  RhRoute: RhRoute,
  TasksRoute: TasksRoute,
  UniformesRoute: UniformesRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
