/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UniformesRouteImport } from './routes/uniformes'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RhRouteImport } from './routes/rh'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InadimplenciaRouteImport } from './routes/inadimplencia'
import { Route as FundosRouteImport } from './routes/fundos'
import { Route as FluxoFuturoRouteImport } from './routes/fluxo-futuro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as CobrancaRouteImport } from './routes/cobranca'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdmissoesRouteImport } from './routes/admissoes'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UniformesRoute = UniformesRouteImport.update({
  id: '/uniformes',
  path: '/uniformes',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InadimplenciaRoute = InadimplenciaRouteImport.update({
  id: '/inadimplencia',
  path: '/inadimplencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FundosRoute = FundosRouteImport.update({
  id: '/fundos',
  path: '/fundos',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoFuturoRoute = FluxoFuturoRouteImport.update({
  id: '/fluxo-futuro',
  path: '/fluxo-futuro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaRoute = CobrancaRouteImport.update({
  id: '/cobranca',
  path: '/cobranca',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissoesRoute = AdmissoesRouteImport.update({
  id: '/admissoes',
  path: '/admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/agenda': typeof AgendaRoute
  '/cobranca': typeof CobrancaRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fluxo-futuro': typeof FluxoFuturoRoute
  '/fundos': typeof FundosRoute
  '/inadimplencia': typeof InadimplenciaRoute
  '/onboarding': typeof OnboardingRoute
  '/rh': typeof RhRoute
  '/tasks': typeof TasksRoute
  '/uniformes': typeof UniformesRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/agenda': typeof AgendaRoute
  '/cobranca': typeof CobrancaRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fluxo-futuro': typeof FluxoFuturoRoute
  '/fundos': typeof FundosRoute
  '/inadimplencia': typeof InadimplenciaRoute
  '/onboarding': typeof OnboardingRoute
  '/rh': typeof RhRoute
  '/tasks': typeof TasksRoute
  '/uniformes': typeof UniformesRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/agenda': typeof AgendaRoute
  '/cobranca': typeof CobrancaRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fluxo-futuro': typeof FluxoFuturoRoute
  '/fundos': typeof FundosRoute
  '/inadimplencia': typeof InadimplenciaRoute
  '/onboarding': typeof OnboardingRoute
  '/rh': typeof RhRoute
  '/tasks': typeof TasksRoute
  '/uniformes': typeof UniformesRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissoes'
    | '/agenda'
    | '/cobranca'
    | '/conciliacao'
    | '/configuracoes'
    | '/fluxo-futuro'
    | '/fundos'
    | '/inadimplencia'
    | '/onboarding'
    | '/rh'
    | '/tasks'
    | '/uniformes'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissoes'
    | '/agenda'
    | '/cobranca'
    | '/conciliacao'
    | '/configuracoes'
    | '/fluxo-futuro'
    | '/fundos'
    | '/inadimplencia'
    | '/onboarding'
    | '/rh'
    | '/tasks'
    | '/uniformes'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/admissoes'
    | '/agenda'
    | '/cobranca'
    | '/conciliacao'
    | '/configuracoes'
    | '/fluxo-futuro'
    | '/fundos'
    | '/inadimplencia'
    | '/onboarding'
    | '/rh'
    | '/tasks'
    | '/uniformes'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissoesRoute: typeof AdmissoesRoute
  AgendaRoute: typeof AgendaRoute
  CobrancaRoute: typeof CobrancaRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FluxoFuturoRoute: typeof FluxoFuturoRoute
  FundosRoute: typeof FundosRoute
  InadimplenciaRoute: typeof InadimplenciaRoute
  OnboardingRoute: typeof OnboardingRoute
  RhRoute: typeof RhRoute
  TasksRoute: typeof TasksRoute
  UniformesRoute: typeof UniformesRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uniformes': {
      id: '/uniformes'
      path: '/uniformes'
      fullPath: '/uniformes'
      preLoaderRoute: typeof UniformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inadimplencia': {
      id: '/inadimplencia'
      path: '/inadimplencia'
      fullPath: '/inadimplencia'
      preLoaderRoute: typeof InadimplenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundos': {
      id: '/fundos'
      path: '/fundos'
      fullPath: '/fundos'
      preLoaderRoute: typeof FundosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-futuro': {
      id: '/fluxo-futuro'
      path: '/fluxo-futuro'
      fullPath: '/fluxo-futuro'
      preLoaderRoute: typeof FluxoFuturoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca': {
      id: '/cobranca'
      path: '/cobranca'
      fullPath: '/cobranca'
      preLoaderRoute: typeof CobrancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissoes': {
      id: '/admissoes'
      path: '/admissoes'
      fullPath: '/admissoes'
      preLoaderRoute: typeof AdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissoesRoute: AdmissoesRoute,
  AgendaRoute: AgendaRoute,
  CobrancaRoute: CobrancaRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FluxoFuturoRoute: FluxoFuturoRoute,
  FundosRoute: FundosRoute,
  InadimplenciaRoute: InadimplenciaRoute,
  OnboardingRoute: OnboardingRoute,
  RhRoute: RhRoute,
  TasksRoute: TasksRoute,
  UniformesRoute: UniformesRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
