// This file is automatically generated. Do not edit it directly.
// EXCEÇÃO MANUAL (não perder se o arquivo for regenerado): `global.fetch` usa
// `fetchComAlarmeDeTeto` (src/lib/supabase-alarme-teto.ts), que só lê o cabeçalho
// Content-Range e dá console.warn quando uma leitura sem paginação volta com
// exatamente 1000 linhas (teto do PostgREST). Ver
// .agents/skills/leitura-sem-limite-crm-escolar/SKILL.md.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { fetchComAlarmeDeTeto } from '@/lib/supabase-alarme-teto';

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: { fetch: fetchComAlarmeDeTeto() },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

